"""Interactive setup wizard for Recall (post-install).

Run after ``pip install typed-recall``:

    recall-setup           # full interactive flow
    recall-setup --yes     # use defaults, no prompts
    recall-setup --client claude-code --openai-key sk-...

The wizard collects:
  - OpenAI / TokenRouter API key (for real bounded_generate)
  - Base URL + model
  - Default DB directory
  - Optional MCP-client registration (Codex / Claude Code / Cursor / Windsurf)

Writes ``~/.recall/.env`` so the library, CLI, and MCP server pick up the
config automatically (auto-loaded on import via ``python-dotenv``).

Also pre-warms the BGE embedder cache on first run so subsequent
``Memory(...)`` instantiation is fast.
"""
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Optional


# -------------- helpers --------------

def _which(cmd: str) -> Optional[str]:
    return shutil.which(cmd)


def _ask(label: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    try:
        ans = input(f"{label}{suffix}: ").strip()
    except (EOFError, KeyboardInterrupt):
        print()
        return default
    return ans or default


def _yesno(label: str, default: bool = False) -> bool:
    suffix = "Y/n" if default else "y/N"
    try:
        ans = input(f"{label} [{suffix}]: ").strip().lower()
    except (EOFError, KeyboardInterrupt):
        print()
        return default
    if not ans:
        return default
    return ans.startswith("y")


def _pick(label: str, choices: list[tuple[str, str, str]], default: str) -> str:
    """Numbered menu. choices = [(value, label, detail), ...]."""
    print(label)
    for i, (_, lab, det) in enumerate(choices, 1):
        print(f"  {i}. {lab}" + (f"  — {det}" if det else ""))
    try:
        ans = input(f"Choice [{default}]: ").strip()
    except (EOFError, KeyboardInterrupt):
        print()
        return default
    if not ans:
        return default
    if ans.isdigit():
        idx = int(ans) - 1
        if 0 <= idx < len(choices):
            return choices[idx][0]
    for v, _, _ in choices:
        if v.lower() == ans.lower():
            return v
    return default


# -------------- env file writer --------------

def _config_dir() -> Path:
    p = Path.home() / ".recall"
    p.mkdir(parents=True, exist_ok=True)
    return p


def write_env_file(values: dict[str, str]) -> Path:
    """Write a dotenv-format file. Quote values that need it."""
    env_path = _config_dir() / ".env"
    # Preserve any existing keys we don't override
    existing: dict[str, str] = {}
    if env_path.exists():
        for line in env_path.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            existing[k.strip()] = v.strip()
    existing.update({k: v for k, v in values.items() if v})
    lines = ["# Recall config — generated by `recall-setup`. Auto-loaded on import.\n"]
    for k, v in sorted(existing.items()):
        # Quote if contains spaces or special chars
        v_str = str(v)
        if any(c in v_str for c in [" ", "#", '"', "'", "$"]):
            v_str = '"' + v_str.replace('"', '\\"') + '"'
        lines.append(f"{k}={v_str}\n")
    env_path.write_text("".join(lines))
    env_path.chmod(0o600)  # restrict, since this may contain API keys
    return env_path


# -------------- MCP client registration --------------

def _make_env_block(values: dict[str, str]) -> dict[str, str]:
    """Subset of values that should be passed via the MCP client's env block."""
    keys = ("OPENAI_API_KEY", "OPENAI_BASE_URL", "RECALL_OPENAI_MODEL", "RECALL_DB_DIR")
    return {k: v for k, v in values.items() if v and k in keys}


def register_codex(values: dict[str, str]) -> bool:
    cfg_path = Path.home() / ".codex" / "config.toml"
    cfg_path.parent.mkdir(parents=True, exist_ok=True)
    content = cfg_path.read_text() if cfg_path.exists() else ""
    # Strip prior recall block (best-effort)
    import re
    content = re.sub(
        r"\n*# ─── Recall.*?(?=\n\[(?!mcp_servers\.recall)|\Z)",
        "",
        content,
        flags=re.DOTALL,
    )
    content = re.sub(
        r"\n*\[mcp_servers\.recall\][\s\S]*?(?=\n\[(?!mcp_servers\.recall\.)|\Z)",
        "",
        content,
        flags=re.DOTALL,
    )
    content = re.sub(
        r"\n*\[mcp_servers\.recall\.env\][\s\S]*?(?=\n\[(?!mcp_servers\.recall\.)|\Z)",
        "",
        content,
        flags=re.DOTALL,
    )
    block = "\n# ─── Recall — typed-edge memory MCP server ───\n"
    block += "[mcp_servers.recall]\n"
    block += 'command = "recall-mcp"\n'
    block += 'args = []\n'
    env = _make_env_block(values)
    if env:
        block += "[mcp_servers.recall.env]\n"
        for k, v in env.items():
            block += f'{k} = "{v}"\n'
    cfg_path.write_text(content.rstrip() + "\n" + block)
    print(f"  ✓ Wrote MCP entry to {cfg_path}")
    return True


def register_claude_code(values: dict[str, str]) -> bool:
    if not _which("claude"):
        print("  ⚠ `claude` CLI not on PATH; skipping. Run manually:")
        print("       claude mcp add recall -- recall-mcp")
        return False
    subprocess.run(["claude", "mcp", "remove", "recall", "--scope", "user"],
                   capture_output=True, check=False)
    args = ["claude", "mcp", "add", "recall", "--scope", "user"]
    for k, v in _make_env_block(values).items():
        args.extend(["-e", f"{k}={v}"])
    args.extend(["--", "recall-mcp"])
    r = subprocess.run(args, check=False)
    if r.returncode == 0:
        print("  ✓ Registered with Claude Code (user scope)")
        return True
    print("  ⚠ `claude mcp add` failed; you can run manually:")
    print("       claude mcp add recall -- recall-mcp")
    return False


def register_cursor(values: dict[str, str]) -> bool:
    import json
    p = Path.home() / ".cursor" / "mcp.json"
    p.parent.mkdir(parents=True, exist_ok=True)
    cfg = {"mcpServers": {}}
    if p.exists():
        try:
            cfg = json.loads(p.read_text())
        except Exception:
            cfg = {"mcpServers": {}}
        cfg.setdefault("mcpServers", {})
    env = _make_env_block(values)
    cfg["mcpServers"]["recall"] = {"command": "recall-mcp", "args": []}
    if env:
        cfg["mcpServers"]["recall"]["env"] = env
    p.write_text(json.dumps(cfg, indent=2))
    print(f"  ✓ Wrote MCP entry to {p}")
    return True


def register_windsurf(values: dict[str, str]) -> bool:
    import json
    p = Path.home() / ".codeium" / "windsurf" / "mcp_config.json"
    p.parent.mkdir(parents=True, exist_ok=True)
    cfg = {"mcpServers": {}}
    if p.exists():
        try:
            cfg = json.loads(p.read_text())
        except Exception:
            cfg = {"mcpServers": {}}
        cfg.setdefault("mcpServers", {})
    env = _make_env_block(values)
    cfg["mcpServers"]["recall"] = {"command": "recall-mcp", "args": []}
    if env:
        cfg["mcpServers"]["recall"]["env"] = env
    p.write_text(json.dumps(cfg, indent=2))
    print(f"  ✓ Wrote MCP entry to {p}")
    return True


CLIENT_DETECTORS = {
    "codex":       lambda: (Path.home() / ".codex" / "config.toml").exists() or (Path.home() / ".codex").exists(),
    "claude-code": lambda: bool(_which("claude")),
    "cursor":      lambda: (Path.home() / ".cursor").exists() or (Path.home() / "Library" / "Application Support" / "Cursor").exists(),
    "windsurf":    lambda: (Path.home() / ".codeium" / "windsurf").exists() or (Path.home() / "Library" / "Application Support" / "Windsurf").exists(),
}

CLIENT_REGISTRARS = {
    "codex":       register_codex,
    "claude-code": register_claude_code,
    "cursor":      register_cursor,
    "windsurf":    register_windsurf,
}


# -------------- BGE prefetch (optional) --------------

def prefetch_bge_model(model_name: str = "BAAI/bge-small-en-v1.5") -> None:
    """Download the BGE weights into HuggingFace's cache so the first
    Memory(...) call is fast."""
    try:
        from sentence_transformers import SentenceTransformer  # type: ignore
    except ImportError:
        print("  ⚠ sentence-transformers not installed; skipping model pre-fetch.")
        return
    print(f"  Downloading {model_name} (one-time, ~33MB)...")
    SentenceTransformer(model_name)
    print("  ✓ BGE model cached.")


# -------------- main --------------

def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        prog="recall-setup",
        description="Recall — interactive post-install setup.",
    )
    p.add_argument("--yes", "-y", action="store_true", help="Skip prompts; use defaults.")
    p.add_argument("--client", default=None,
                   help="codex | claude-code | cursor | windsurf | all | none")
    p.add_argument("--openai-key", dest="openai_key", default=None)
    p.add_argument("--openai-base-url", dest="openai_base_url", default=None)
    p.add_argument("--openai-model", dest="openai_model", default=None)
    p.add_argument("--db-dir", dest="db_dir", default=None)
    p.add_argument("--no-prefetch", action="store_true",
                   help="Skip downloading the BGE model now.")
    args = p.parse_args(argv)

    print("\nRecall — post-install setup\n")

    detected = {k: fn() for k, fn in CLIENT_DETECTORS.items()}
    if args.yes or args.client is not None:
        # non-interactive
        c = (args.client or "none").lower()
        chosen = (
            list(CLIENT_REGISTRARS.keys()) if c == "all"
            else [] if c == "none"
            else [s.strip() for s in c.split(",") if s.strip()]
        )
        openai_key = args.openai_key or ""
        openai_base_url = args.openai_base_url or ""
        openai_model = args.openai_model or ""
        db_dir = args.db_dir or str(Path.home() / ".recall")
    else:
        # interactive
        print("Detected MCP clients on this machine:")
        for k, v in detected.items():
            print(f"  {'✓' if v else '·'} {k}")
        print()

        choice = _pick(
            "Which MCP client(s) to register with?",
            [
                ("codex",       "Codex CLI",        "writes ~/.codex/config.toml"),
                ("claude-code", "Claude Code",      "claude mcp add recall (user scope)"),
                ("cursor",      "Cursor",           "writes ~/.cursor/mcp.json"),
                ("windsurf",    "Windsurf",         "writes ~/.codeium/windsurf/mcp_config.json"),
                ("all",         "All of the above", ""),
                ("none",        "Skip — just save config", ""),
            ],
            "all",
        )
        chosen = (
            list(CLIENT_REGISTRARS.keys()) if choice == "all"
            else [] if choice == "none"
            else [choice]
        )
        print()

        want_llm = _yesno("Configure an OpenAI / TokenRouter API key for real bounded_answer?", default=False)
        if want_llm:
            openai_key      = _ask("  API key (input echoed — paste from a keychain if needed)")
            openai_base_url = _ask("  Base URL", default="https://api.openai.com/v1")
            openai_model    = _ask("  Model", default="gpt-4o-mini")
        else:
            openai_key = ""
            openai_base_url = ""
            openai_model = ""
        print()

        db_dir = _ask("Default DB directory", default=str(Path.home() / ".recall"))
        print()

    # ------ write config ------
    values = {
        "OPENAI_API_KEY":     openai_key,
        "OPENAI_BASE_URL":    openai_base_url,
        "RECALL_OPENAI_MODEL": openai_model,
        "RECALL_DB_DIR":      db_dir,
    }
    env_path = write_env_file(values)
    print(f"✓ Wrote config to {env_path}\n")

    # ------ register MCP clients ------
    if chosen:
        print("Registering MCP server with chosen client(s):")
        for c in chosen:
            fn = CLIENT_REGISTRARS.get(c)
            if fn:
                fn(values)
        print()

    # ------ optional model prefetch ------
    if not args.no_prefetch:
        try:
            print("Pre-fetching BGE model so first Memory(...) call is fast:")
            prefetch_bge_model()
            print()
        except Exception as e:
            print(f"  ⚠ pre-fetch skipped: {e}\n")

    # ------ summary ------
    print("✅ Setup complete.\n")
    if chosen:
        print("Restart your MCP client(s) to load `recall`.\n")
    print("Try:")
    print("  recall me add 'first memory'")
    print("  recall me ask 'what was my first memory?'")
    print("  recall me health\n")
    print("Docs: https://github.com/yash194/recall\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
